CREATE TABLE audit_logs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    event_type   VARCHAR(50)  NOT NULL,
    entity_type  VARCHAR(50),
    entity_id    BIGINT,
    description  VARCHAR(500) NOT NULL,
    performed_by VARCHAR(100)
);

CREATE INDEX idx_audit_occurred_at  ON audit_logs (occurred_at DESC);
CREATE INDEX idx_audit_entity_type  ON audit_logs (entity_type);
