CREATE TABLE tariffs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100)  NOT NULL,
    category      VARCHAR(50)   NOT NULL,
    annual_fee_kr DECIMAL(10,2) NOT NULL,
    valid_from    DATE          NOT NULL,
    valid_to      DATE,
    description   VARCHAR(500)
);

ALTER TABLE slips ADD COLUMN category VARCHAR(50);
